# Gradle
org.gradle.jvmargs = -Xmx6G
org.gradle.parallel = true
org.gradle.daemon = false
fabric.loom.ignoreDependencyLoomVersionValidation = true
fabric.loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

# Project
mod_id = courier_owls
mod_name = Courier Owls
mod_version = 26.1.2-1.0.0-beta
mod_author = MehVahdJukaar
mod_description = Owl babies
mod_license = Supplementaries Team License v.1.5
mod_authors = MehVahdJukaar
mod_homepage = https://github.com/MehVahdJukaar/courier_owls
mod_credits = MehVahdJukaar
mod_github = https://github.com/MehVahdJukaar/courier_owls

release_type = release
maven_group = net.mehvahdjukaar
repository = MehVahdJukaar/courier_owls
#modrinth_project_id = courier_owls
curseforge_project_id = 1675546

# MC / loader versions
mc_version = 26.1.2

neoforge_version = 26.1.2.94
neoForge.neoFormRuntime.version = 2.0.25

fabric_loader_version = 0.19.3
fabric_api_version = 0.155.2+26.1.2

# Mod-specific dep versions
moonlight_version = 26.1.2-4.0.1c
moonlight_min_version = 26.1.2-4.0.0
codecui_version = 26.1.2-1.4.3
supplementaries_version = 1.21.1-3.9.1
